### ISSUE TITLE
Archiving using Xcode 15.3 Fails Due when Including PPRiskMagnes.framework (minimum OS Version specified in the Info.plist)

### ISSUE THREAD

**Issue by RGG-jayoung** [braintree/braintree_ios#1229]
### Braintree SDK Version

6.14.0-16.16.0

### Environment

Both

### Xcode Version

Xcode 15.3

### OS Version & Device

iOS 17.x

### Integration type

Swfit Package Manager

### Development Processor

Both

### Describe the bug

When including PPRiskMagnes.framework, archiving builds fail using Xcode 15.3 locally or using Xcode Cloud. See screenshot.

Previously mentioned here when attempting to submit Privacy Manifest compatible releases to Apple.
https://github.com/braintree/braintree_ios/issues/1135#issuecomment-1985951137

### To reproduce

Using Xcode 15.3:
1. Product > Archive
2. Organizer > Validate App

Using Xcode Cloud with Xcode 15.3 selected produces the same result.

### Expected behavior

Archiving the app with Braintree SDK links should work with Xcode 15.3 and pass Apple validation. These errors were once visible for other dependencies like Google Firebase, Crashlytics, etc. but the latest releases of those SDKs resolved this. The only dependency that exhibits this failure is `PPRiskMagnes.framework`. This blocks us from shipping new releases or updates. Given that all other vendors have resolved this issue, and Braintree is the outlier we believe Braintree needs to address this.

A workaround of archiving with Xcode 15.2 was mentioned as a solution, but this fails with the same validation error. This started failing on March 13, Apple's announced deadline for Privacy manifest submissions. While these issue are technically unrelated, Apple's validation scan's seem stricter about the contents of the .ipa file and the `PPRiskMagnes.framework`. 

Please advise.

### Screenshots

<img width="1159" alt="311287460-452ecf4f-72d5-49a2-88d6-b201fc147a19" src="https://github.com/braintree/braintree_ios/assets/53495188/f6c29c74-ce0b-4597-a128-1e85b2685ad8">

**Comment by KunJeongPark** [comment]
Hello, 
   Which version of the SDK are you using? We just released 6.15.0 with updates with Magnes version with its own Privacy Manifest yesterday, March 18th.

**Comment by RGG-jayoung** [comment]
Hi @KunJeongPark thank you for the quick response. 

- Braintree SDK 16.16.0 (also tried this with 16.14.0, 16.15.0).
- Minimum Deployment Target: iOS 15.1

<img width="777" alt="image" src="https://github.com/braintree/braintree_ios/assets/53495188/3d6dfd03-049e-46da-ad28-e5cb566ed4a8">

<img width="542" alt="image" src="https://github.com/braintree/braintree_ios/assets/53495188/154450c7-7915-469f-8e46-501f8ba4ef68">

**Comment by KunJeongPark** [comment]
Thank you.

**Comment by KunJeongPark** [comment]
I was able to successfully archive our demo app with min deployment changed to 15.1 using Xcode 15.3
Let me investigate to see if I can reproduce this error and also check with my team.

**Comment by RGG-jayoung** [comment]
> I was able to successfully archive our demo app with min deployment changed to 15.1 using Xcode 15.3 with our latest SDK, 6.16.0. The Magnes version that we used in the new releases was built with Xcode 14.1, I believe. This should be compatible with your minimum deployment target.
> 
> I'm wondering if it could be issue with Xcode holding on to cached data. Have you tried removing derived data?
> 
> Let me investigate to see if I can reproduce this error and also check with my team.

Thank you @KunJeongPark. Just cleared derived data and clean build and still seeing the error message.  Definitely spooky behavior.

To rule a few more things out, I'm doing some additional tests and will let you know as soon as possible. We have a test app that is free of other dependencies that I can link to Braintree 6.16.0 and see if that builds and validates.

**Comment by KunJeongPark** [comment]
Thank you. I just tested archiving a new app using SPM and versions that you indicated and I was also able to successfully archive the app with a team member. Please let us know if there are any details in your implementation that might be relevant for us to investigate.

**Comment by RGG-jayoung** [comment]
After a lot of experimentation, the validation during submission still fails. Findings below:

We saw Firebase listed in a similar fashion, accounting for about 30-60 errors on validation. After updating to the latest version, their workaround modifies their minimum OS version to be "100". This works, clearing out all the errors except `PPRiskMagnes.framework`.

After archiving the build and opening the .ipa file, here are the contents of the Info.plist of these 2 for comparison.

<img width="1323" alt="image" src="https://github.com/braintree/braintree_ios/assets/53495188/d3dcc241-ccb2-45e9-ba4b-0808c13911bd">

<img width="246" alt="image" src="https://github.com/braintree/braintree_ios/assets/53495188/7c683d43-e422-4033-aca5-880ced26fb46">

Validating the app against the store produces the following error (either through Xcode > Organizer > Validate App) or using Xcode Cloud via CI.

<img width="767" alt="Validation Fails" src="https://github.com/braintree/braintree_ios/assets/53495188/f4583cd3-439f-416d-9fe8-04516f4918ee">

If you modify the PPRiskMagnes.framework > Info.plist inside of the archive, and then submit it again for validation it passes. So its really just the value of this string provided by the framework blocking the validation.

<img width="767" alt="Validation Succeeds" src="https://github.com/braintree/braintree_ios/assets/53495188/bcf78aef-c27a-41c1-9f62-167f74b9ff52">

While we could technically implement a post release script as a workaround, it feels quite wrong to be manipulating a framework's internal contents that we don't own.

**Comment by KunJeongPark** [comment]
I apologize, I misunderstood your original question, I thought you had failure in archiving and now I see the error was in the validation. I see the same error in validation and I do see the Info.plist showing` MinimumOSVersion` as 11.0 in the same Info.plist file. 

I will discuss this with my team tomorrow to see if we need to reach out to the Magnes team.

**Comment by KunJeongPark** [comment]
Hello, 
   I was able to resolve this issue by building our demo app with Xcode 15.2.

**Comment by RGG-jayoung** [comment]
> Hello, I was able to resolve this issue by building our demo app with Xcode 15.2.

Good to hear. Similar to Firebase and others implementing the workaround in their frameworks, what is the plan for PPRiskManges.framework to build with Xcode 15.3 moving forward?

**Comment by KunJeongPark** [comment]
I will contact them about this issue. We were focused so far on trying to figure out a work around so that you can get 
your app approved.

**Comment by RGG-jayoung** [comment]
Appreciate your follow up and us getting to a solution. I'll try to get an answer today on our Xcode 15.2 + Braintree v6. Ideally a Xcode 15.3 solution materializes while we QA our migration.

**Comment by KunJeongPark** [comment]
Thank you, this appears to be an Apple bug, seems like many have filed radars for this issue.

I have contacted Magnes and we are in discussion to see if the issue is only the Apple bug.

**Comment by RGG-jayoung** [comment]
@KunJeongPark did the Magnes team provide any updates on packaging with Xcode 15.3? Any sense on timing.

**Comment by RGG-jayoung** [comment]
We're temporarily downgrading to Xcode 15.2 which is working for submission. While this works, it feels brittle and ideally we should be targeting the latest iOS release. Since Apple introduced the Xcode 15.0 minimum deployment version, I wouldn't be surprised if they chose to enforce 15.3 sometime with all these other requirements in flight.

Thank you for your help and hard work.
