### ISSUE TITLE
Braintree/Braintree-Swift.h file not found using CocoaPods

### ISSUE THREAD

**Issue by ivansnek** [braintree/braintree_ios#651]
**Integration Details:**
 - Braintree SDK Version:  `5.2.0`
 - Environment: Sandbox, Staging and Production
 - iOS Version: 14.0
 - Device: Not applicable (ATM we're not able to finish build process)
 - Integration type & version: CocoaPods 1.10.1

**Describe the bug**
- We've been using Brain tree for a while in our React Native app, previously used `4.36.1`, we're now updating to latest `5.2.0`
- We're using CocoaPods to include the dependency
- When updating to `5.2.0` we get an error at build type in regards a file not found `'Braintree/Braintree-Swift.h' file not found`
- Since there's no official React Native package, we created an internal wrapper around the both native SDK's
- We have followed the [v5 Migration guide](https://github.com/braintree/braintree_ios/blob/master/V5_MIGRATION.md) but is not very useful for our RN&CocoaPods integration
NOTE: We're not using the DropIn integration
- Inside the wrapper project for iOS, we're using the following inside the header file:
```
#import "BraintreeCore.h"
#import "BraintreeCard.h"
```

I have tested with different import headers:
```
#import <Braintree/BraintreeCore.h>
---
#import <Braintree/Braintree.h>
#import <Braintree/BraintreeCard.h>
---
#import "BraintreeCore.h"
#import "BTCardNonce.h"
```

**To Reproduce**
1. There's no explicit steps to reproduce, other than try to update the version

**Expected behavior**
Success build with the latest SDK

**Screenshots**
<img width="1252" alt="Screen Shot 2021-03-22 at 2 34 54 p m" src="https://user-images.githubusercontent.com/1279062/112054982-e490ba00-8b1b-11eb-89ca-d9456e6de712.png">

**Comment by scannillo** [comment]
Hi @ivansnek - we don't offer official support for React Native, as you know. I just made a sample Swift app that included Braintree via CocoaPods (`pod 'Braintree', '~> 5.2.0`) and don't see this issue.

Does your application use Swift? If so - what version?

**Comment by ivansnek** [comment]
@scannillo Yes, we implemented the library on the native side, and just created a bridge to access Braintree methods from JS.
We use Objective-C as the default language on iOS (This is the default on React Native) but we do support swift code inside the app, using a `Objective-C bridging header`. It seems we support Swift 5

Is there an Objective-C sample app where I can see how the library is implemented with CocoaPods?

Also one thing to notice here, we're not currently supporting PayPal, is there a way to not include PayPal Pod/library within the Braintree implementation? As you can see in the error, the exception is thrown on a PayPal related file

**Comment by scannillo** [comment]
Hi @ivansnek. 

> It seems we support Swift 5

Our SDK requires Swift 5.1, since Swift 5.1 includes module stability. Can't hurt to double check this on your end.

> Is there an Objective-C sample app where I can see how the library is implemented with CocoaPods?

No, we don't have a demo to show this. Our repo has a [demo app](https://github.com/braintree/braintree_ios/tree/master/Demo) written in ObjC & Swift, but it doesn't pull in Braintree via CocoaPods. It could be helpful if you're looking for some example code, though.

> Also one thing to notice here, we're not currently supporting PayPal, is there a way to not include PayPal Pod/library within the Braintree implementation?

Yes! You can only include the modules you need with the following syntax in your Podfile:

```
pod 'Braintree/Core'
pod 'Braintree/Card'
pod 'Braintree/ApplePay'
... etc
```

If you do `pod 'Braintree'`, this will include the Core, Card, & PayPal [subspecs automatically](https://github.com/braintree/braintree_ios/blob/987e9610fb7c9deaa074fc3e9f50588d320ac25a/Braintree.podspec#L23).

Let us know if this resolves your issue.

**Comment by ivansnek** [comment]
@scannillo Thank you! the last part resolved my issue, using isolated modules, in my case

```
pod 'Braintree/Core'
pod 'Braintree/Card'
```

I didn't found why on building time that header file didn't exists.

**Comment by jbatra-umeey** [comment]
@ivansnek I am curious to understand how did u resolve the issue. I am still getting the same error in my react-native APp

Podfile :

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

target 'paypalExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'paypalExampleTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'paypalExample-tvOS' do
  # Pods for paypalExample-tvOS

  target 'paypalExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

pod 'Braintree/Core'
pod 'Braintree/PayPal'
```

My podspec

```
Pod::Spec.new do |s|
  s.name         = "PaypalDemo"
  s.version          = package['version']
  s.summary          = package['name']
  s.license          = package['license']
  s.description  = package['description']
  s.homepage     = "URL"
  s.author             = "Umeey"
  s.platform     = :ios, "12.0"
  s.source       = { URL }
  s.source_files  = "ios/**/*.{h,m}"
  s.dependency "React"
  s.dependency "Braintree/Core"
  s.dependency "Braintree/PayPal"
end
```

**Comment by ivansnek** [comment]
@jbatra-umeey can you try placing the pods inside the `target 'paypalExample'` I think that might be your issue

**Comment by jbatra-umeey** [comment]
@ivansnek yes sure. Can you please share your podfile if possible ?

**Comment by jbatra-umeey** [comment]
@ivansnek  I tried the same but no luck. I see that you are not using Paypal. Could you please try to include Paypal and verify the behavior at your end?

**Comment by ivansnek** [comment]
@jbatra-umeey Actually we use only the individual packages due to an error with PayPal, as you can see in the first image.
